---
- name: Show version
  hosts: 10.22.1.1
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Run 'show version' command
      cisco.ios.ios_command:
        commands:
          - show version
