---
- name: Show running configuration
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
  tasks:
    - name: Run show running-config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines
