---
- name: cisco_sh_ver
  hosts: all
  gather_facts: no
  vars: # for execution environment
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands:
     - show version
