---
- name: Show running configuration
  hosts: 10.22.1.1
  gather_facts: no
  tasks:
    - name: Run show running-config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines
