---
- name: Show version
  hosts: 10.22.1.1
  gather_facts: no
  ansible_ssh_extra_args: '-T'  # Thêm tùy chọn này
  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands: show version
