---
- name: cisco_sh_ver
  hosts: all
  gather_facts: no
  vars: # for execution environment
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands:
     - show version       
  - name: show run on remote devices
    become: true
    cisco.ios.ios_command:
     commands: 
     - show run
